
CREATE TABLE CAR_NAME
(
  CARS      VARCHAR(50) NOT NULL COMMENT '차이름',
  CARS_CODE VARCHAR(50) NOT NULL COMMENT '고유ID',
  PRIMARY KEY (CARS_CODE)
) COMMENT '차이름';

CREATE TABLE CARS_INFORMATION
(
  Model Year      INTEGER(50) NOT NULL COMMENT '연식',
  COMPANY_CODE_ID VARCHAR(50) NOT NULL COMMENT '회사이름',
  CARS_CODE_ID    VARCHAR(50) NOT NULL COMMENT '차이름',
  CARS_ID         VARCHAR(50) NOT NULL COMMENT '유니크_ID',
  PRIMARY KEY (CARS_ID)
) COMMENT '차정보';

CREATE TABLE CARS_OPTION
(
  OPTION         VARCHAR(50) NOT NULL COMMENT '옵션',
  CARS_OPTION_ID VARCHAR(50) NOT NULL COMMENT '차 옵션 ID',
  PRIMARY KEY (CARS_OPTION_ID)
) COMMENT '차옵션';

CREATE TABLE COMPANY_NAME
(
  COMPANY      VARCHAR(50) NOT NULL COMMENT '회사명',
  COMPANY_CODE VARCHAR(50) NOT NULL COMMENT '고유ID',
  PRIMARY KEY (COMPANY_CODE)
) COMMENT '회사이름';

CREATE TABLE Unique ID
(
  CARS_ID        VARCHAR(50) NOT NULL COMMENT '차 옵션 ID ',
  CARS_OPTION_ID VARCHAR(50) NOT NULL COMMENT '차 ID'
);

ALTER TABLE Unique ID
  ADD CONSTRAINT FK_CARS_OPTION_TO_Unique ID
    FOREIGN KEY (CARS_ID)
    REFERENCES CARS_OPTION (CARS_OPTION_ID);

ALTER TABLE CARS_INFORMATION
  ADD CONSTRAINT FK_COMPANY_NAME_TO_CARS_INFORMATION
    FOREIGN KEY (COMPANY_CODE_ID)
    REFERENCES COMPANY_NAME (COMPANY_CODE);

ALTER TABLE CARS_INFORMATION
  ADD CONSTRAINT FK_CAR_NAME_TO_CARS_INFORMATION
    FOREIGN KEY (CARS_CODE_ID)
    REFERENCES CAR_NAME (CARS_CODE);

ALTER TABLE Unique ID
  ADD CONSTRAINT FK_CARS_INFORMATION_TO_Unique ID
    FOREIGN KEY (CARS_OPTION_ID)
    REFERENCES CARS_INFORMATION (CARS_ID);
