
CREATE TABLE  MEMBERS_ HOBBY  
(
  HOBBY_CODE_ID         NOT NULL,
  MEMBERS_ID    VARCHAR NOT NULL COMMENT 'UNIQUE_ID'
) COMMENT '회원_취미';

CREATE TABLE  MEMBERS_ Sign Up
(
  Name         VARCHAR NULL     COMMENT '이름',
  Age          INTEGER NULL     COMMENT '나이',
  Address      VARCHAR NULL     COMMENT '주소',
  Phone Number VARCHAR NULL     COMMENT '전화번호',
  MEMBERS_ID   VARCHAR NOT NULL COMMENT 'UNIQUE_ID',
  GENDER_CODE          NOT NULL,
  GENDER_CODE          NOT NULL,
                       NOT NULL,
  PRIMARY KEY (MEMBERS_ID)
) COMMENT '회원정보';

CREATE TABLE  MEMBERS_Login
(
  E-MAIL                    NULL     COMMENT '이메일',
   MEMBERS_LOGIN_ID         NULL     COMMENT '회원 로그인',
   MEMBERS_ID       VARCHAR NOT NULL COMMENT '유니크ID'
) COMMENT '회원정보 로그인';

CREATE TABLE ADDRESS_CODE
(
  ADDRESS          NULL     COMMENT '주소',
  ADDRESS_CODE_ID  NULL    ,
                   NOT NULL,
  PRIMARY KEY ()
) COMMENT '주소코드';

CREATE TABLE GENDER_CODE
(
  GENDER      VARCHAR NULL     COMMENT '성별',
  GENDER_CODE         NOT NULL,
  PRIMARY KEY (GENDER_CODE)
) COMMENT '성별코드';

CREATE TABLE HOBBY_CODE 
(
  HOBBY          NULL     COMMENT '취미명',
  HOBBY_CODE_ID  NOT NULL,
  PRIMARY KEY (HOBBY_CODE_ID)
) COMMENT '취미코드';

ALTER TABLE  MEMBERS_Login
  ADD CONSTRAINT FK_ MEMBERS_ Sign Up_TO_ MEMBERS_Login
    FOREIGN KEY ( MEMBERS_ID)
    REFERENCES  MEMBERS_ Sign Up (MEMBERS_ID);

ALTER TABLE  MEMBERS_ Sign Up
  ADD CONSTRAINT FK_GENDER_CODE_TO_ MEMBERS_ Sign Up
    FOREIGN KEY (GENDER_CODE)
    REFERENCES GENDER_CODE (GENDER_CODE);

ALTER TABLE  MEMBERS_ HOBBY 
  ADD CONSTRAINT FK_HOBBY_CODE _TO_ MEMBERS_ HOBBY 
    FOREIGN KEY (HOBBY_CODE_ID)
    REFERENCES HOBBY_CODE  (HOBBY_CODE_ID);

ALTER TABLE  MEMBERS_ HOBBY 
  ADD CONSTRAINT FK_ MEMBERS_ Sign Up_TO_ MEMBERS_ HOBBY 
    FOREIGN KEY (MEMBERS_ID)
    REFERENCES  MEMBERS_ Sign Up (MEMBERS_ID);

ALTER TABLE  MEMBERS_ Sign Up
  ADD CONSTRAINT FK_ADDRESS_CODE_TO_ MEMBERS_ Sign Up
    FOREIGN KEY ()
    REFERENCES ADDRESS_CODE ();
